trieuconcrete/laravel-admin

- src/app/Facades/Setting.php
- src/app/Http/Controllers/Admin/SettingController.php
- src/app/Http/Requests/Setting/UpdateSettingRequest.php
- src/app/Models/Setting.php
- src/app/Providers/AuthServiceProvider.php
- src/app/Providers/EventServiceProvider.php
- src/app/Providers/SettingServiceProvider.php
- src/app/Repositories/SettingRepository.php
- src/app/Services/SettingService.php
- src/config/app.php
- src/database/migrations/2025_05_31_000000_create_settings_table.php
- src/public/js/settings.js
- src/resources/views/admin/partials/sidebar.blade.php
- src/resources/views/admin/settings/index.blade.php
- src/resources/views/admin/settings/partials/company.blade.php
- src/resources/views/admin/settings/partials/notifications.blade.php
- src/resources/views/admin/settings/partials/shipment.blade.php
- src/resources/views/admin/settings/partials/system.blade.php
- src/routes/web.php
Notes:
run: `php artisan migrate`
> Manager setting

- src/app/Exports/InvoiceExport.php
- src/app/Http/Controllers/Admin/CustomerController.php
- src/app/Http/Requests/Shipment/ShipmentRequest.php
- src/app/Models/Shipment.php
- src/app/Models/ShipmentDeductionType.php
- src/app/Repositories/Eloquent/CustomerRepository.php
- src/app/Repositories/Interface/CustomerRepositoryInterface.php
- src/app/Services/CustomerService.php
- src/composer.json
- src/composer.lock
- src/database/migrations/2025_06_09_095814_add_unit_price_weight_trips_to_shipments_table.php
- src/public/js/shipment-form.js
- src/resources/views/admin/customers/show.blade.php
- src/resources/views/admin/shipments/create.blade.php
- src/resources/views/admin/shipments/edit.blade.php
- src/routes/web.php
> Maanger bang ke

- src/app/Http/Controllers/Admin/CarRentalController.php
- src/app/Http/Requests/CarRental/StoreCarRentalRequest.php
- src/app/Http/Requests/CarRental/UpdateCarRentalRequest.php
- src/app/Models/CarRental.php
- src/app/Models/CarRentalVehicle.php
- src/app/Services/CarRentalService.php
- src/database/migrations/2025_06_13_090413_car_rental.php
- src/database/migrations/2025_06_13_090508_car_rental_vehicles.php
- src/database/seeders/CarRentalSeeder.php
- src/resources/views/admin/car_rental/index.blade.php
```
php artisan db:seed --class=CarRentalSeeder
```
> Feature Car Rental

- src/app/Constants.php
- src/app/Http/Controllers/Admin/SalaryController.php
- src/app/Http/Controllers/Admin/UserController.php
- src/app/Http/Requests/Salary/SyncSalaryRequest.php
- src/app/Http/Requests/SalaryAdvanceRequest/StoreSalaryAdvanceRequestRequest.php
- src/app/Models/SalaryAdvanceRequest.php
- src/app/Models/SalaryDetail.php
- src/app/Models/User.php
- src/app/Providers/RepositoryServiceProvider.php
- src/app/Repositories/Eloquent/SalaryDetailRepository.php
- src/app/Repositories/Eloquent/SalaryPeriodRepository.php
- src/app/Repositories/Interface/SalaryDetailRepositoryInterface.php
- src/app/Repositories/Interface/SalaryPeriodRepositoryInterface.php
- src/app/Services/SalaryService.php
- src/app/Services/UserService.php
- src/database/migrations/2025_06_17_142538_alter_column_table_salary_details.php
- src/database/migrations/2025_06_17_151219_add_column_type_into_salary_advance_requests_table.php
- src/public/js/salary-advance-requests-handler.js
- src/resources/views/admin/salary/index.blade.php
- src/resources/views/admin/users/show.blade.php
- src/routes/web.php
run command: `php artisan migrate`
> Change process salary

- src/app/Exports/SalaryExport.php
- src/app/Http/Controllers/Admin/ShipmentController.php
- src/app/Http/Controllers/Admin/UserController.php
- src/app/Models/Shipment.php
- src/app/Repositories/Eloquent/CustomerRepository.php
- src/app/Services/UserService.php
- src/database/migrations/2025_06_19_155947_change_column_salary_advance_amount_can_nullable.php
- src/database/seeders/ShipmentDeductionTypeSeeder.php
- src/public/js/shipment-form.js
- src/resources/views/admin/shipments/create.blade.php
- src/resources/views/admin/shipments/edit.blade.php
- src/resources/views/admin/shipments/index.blade.php
Run:
```
1. php artisan migrate
2. php artisan db:seed --class=ShipmentDeductionTypeSeeder
```
> Change process export salary & fix some issues

- src/app/Http/Controllers/Admin/CustomerController.php
- src/app/Http/Controllers/Admin/PaymentTransactionController.php
- src/app/Http/Requests/Transaction/SearchTransactionRequest.php
- src/app/Http/Requests/Transaction/StoreTransactionRequest.php
- src/app/Models/Payment.php
- src/app/Models/Transaction.php
- src/app/Providers/RepositoryServiceProvider.php
- src/app/Repositories/Eloquent/PaymentRepository.php
- src/app/Repositories/Eloquent/TransactionRepository.php
- src/app/Repositories/Interface/PaymentRepositoryInterface.php
- src/app/Repositories/Interface/TransactionRepositoryInterface.php
- src/app/Services/TransactionPaymentService.php
- src/database/migrations/2025_06_20_103118_create_payments_tables.php
- src/database/migrations/2025_06_20_103239_create_transactions_tables.php
- src/resources/views/admin/customers/partials/transaction-table.blade.php
- src/resources/views/admin/customers/show.blade.php
- src/resources/views/admin/partials/pagination.blade.php
- src/routes/web.php
run command: `php artisan migrate`
> Add process transactions

- docker-compose.yml
- src/app/Http/Controllers/Admin/ShipmentController.php
- src/app/Http/Requests/Shipment/ShipmentRequest.php
- src/app/Models/Shipment.php
- src/app/Models/ShipmentDeduction.php
- src/app/Models/ShipmentDeductionType.php
- src/app/Repositories/Eloquent/ShipmentRepository.php
- src/app/Repositories/Interface/ShipmentRepositoryInterface.php
- src/app/Services/ShipmentService.php
- src/database/migrations/2025_06_27_081630_add_is_main_driver_shipment_deductions_table.php
- src/database/seeders/ShipmentDeductionTypeSeeder.php
- src/public/js/shipment-form.js
- src/resources/views/admin/shipments/create.blade.php
- src/resources/views/admin/shipments/edit.blade.php
run command:
```
php artisan migrate
php artisan db:seed --class=ShipmentDeductionTypeSeeder
```
https://github.com/trieuconcrete/laravel-admin/issues/82
> Change process choose driver in shipment

- src/app/Http/Controllers/Admin/DashboardController.php
- src/app/Models/SalaryDetail.php
https://github.com/trieuconcrete/laravel-admin/issues/81
> Dashboah income and expense

- src/app/Http/Controllers/Admin/CustomerController.php
- src/app/Models/Customer.php
- src/app/Models/ShipmentReport.php
- src/database/migrations/2025_07_03_201224_create_shipment_reports_table_v2.php
- src/resources/views/admin/customers/show.blade.php
- src/routes/web.php
https://github.com/trieuconcrete/laravel-admin/issues/93
run: php artisan migrate
> <Công nợ khách hàng>Tổng kết công nợ Khách hàng

- src/app/Http/Controllers/Admin/DashboardController.php
- src/app/Http/Controllers/Admin/ShipmentController.php
- src/app/Http/Requests/Shipment/ShipmentRequest.php
- src/app/Services/ShipmentService.php
- src/public/js/shipment-form.js
- src/resources/views/admin/customers/show.blade.php
- src/resources/views/admin/dashboard.blade.php
- src/resources/views/admin/shipments/edit.blade.php
- src/routes/web.php
https://github.com/trieuconcrete/laravel-admin/issues/104
https://github.com/trieuconcrete/laravel-admin/issues/103
https://github.com/trieuconcrete/laravel-admin/issues/101
https://github.com/trieuconcrete/laravel-admin/issues/99
> Fix some issues

- src/app/Http/Controllers/Admin/CustomerController.php
- src/app/Http/Controllers/Admin/ShipmentController.php
- src/app/Http/Controllers/Admin/UserController.php
- src/app/Http/Controllers/Admin/VehicleController.php
https://github.com/trieuconcrete/laravel-admin/issues/101
> handle route

- src/app/Exports/VehicleLogExport.php
- src/app/Http/Controllers/Admin/CarRentalController.php
- src/app/Models/CarRental.php
- src/resources/views/admin/car_rental/edit.blade.php
- src/routes/web.php
https://github.com/trieuconcrete/laravel-admin/issues/108
> Export car_rental_vehicle_logs

- src/resources/views/admin/car_rental/edit.blade.php
- src/resources/views/admin/customers/show.blade.php
https://github.com/trieuconcrete/laravel-admin/issues/108
> Change UI customers detail & car-rental edit

- src/app/Exports/TollFeeDetailExport.php
- src/app/Exports/TollFeeExport.php
- src/app/Exports/VehicleLogWithTollFeeExport.php
- src/app/Http/Controllers/Admin/CarRentalController.php
https://github.com/trieuconcrete/laravel-admin/issues/108
> Download toll fee

- src/app/Http/Controllers/Admin/CustomerController.php
- src/app/Http/Requests/Shipment/ShipmentRequest.php
- src/app/Models/ShipmentReport.php
- src/app/Services/CustomerService.php
- src/app/Services/ShipmentService.php
- src/database/migrations/2025_07_21_201646_add_column_is_finalized_into_shipment_reports_table.php
- src/resources/views/admin/customers/show.blade.php
- src/resources/views/admin/shipments/create.blade.php
https://github.com/trieuconcrete/laravel-admin/issues/114
https://github.com/trieuconcrete/laravel-admin/issues/115
https://github.com/trieuconcrete/laravel-admin/issues/117
run: php artisan migrate
> Issues 114, 115, 117

- src/app/Http/Controllers/Admin/CarRentalController.php
- src/app/Http/Controllers/Admin/CustomerController.php
- src/app/Http/Controllers/Admin/SalaryController.php
- src/app/Repositories/Eloquent/UserRepository.php
- src/app/Services/SalaryService.php
- src/public/js/salary-advance-requests-handler.js
- src/resources/views/admin/car_rental/edit.blade.php
- src/resources/views/admin/customers/show.blade.php
- src/resources/views/admin/salary/index.blade.php
- src/resources/views/admin/users/show.blade.php
- src/routes/web.php
https://github.com/trieuconcrete/laravel-admin/issues/121
https://github.com/trieuconcrete/laravel-admin/issues/120
https://github.com/trieuconcrete/laravel-admin/issues/108#issuecomment-3066333346
> Issues 121 + 120 + 108 + 122 + 85

- src/app/Exports/VehicleLogExport.php
- src/app/Http/Controllers/Admin/CarRentalController.php
- src/app/Http/Requests/CarRental/UpdateCarRentalRequest.php
- src/app/Models/CarRental.php
- src/app/Services/CarRentalService.php
- src/resources/views/admin/car_rental/edit.blade.php
https://github.com/trieuconcrete/laravel-admin/issues/134
> Issues 134

- src/app/Exports/SalaryExport.php
- src/app/Http/Controllers/Admin/SalaryController.php
- src/app/Http/Controllers/Admin/UserController.php
- src/app/Http/Requests/Shipment/ShipmentRequest.php
- src/app/Models/Shipment.php
- src/app/Models/ShipmentDeductionType.php
- src/app/Models/User.php
- src/app/Services/SalaryService.php
- src/app/Services/ShipmentService.php
- src/app/Services/UserService.php
- src/database/migrations/2025_07_29_113015_add_ghi_chu_to_shipment_deduction_types.php
- src/database/migrations/2025_07_29_114515_add_notes_column_to_shipment_deduction_types.php
- src/public/js/shipment-form.js
- src/resources/views/admin/car_rental/edit.blade.php
- src/resources/views/admin/salary/index.blade.php
- src/resources/views/admin/shipments/create.blade.php
- src/resources/views/admin/shipments/edit.blade.php
- src/resources/views/admin/shipments/index.blade.php
- src/resources/views/admin/users/partials/salary-table.blade.php
- src/resources/views/admin/users/show.blade.php
https://github.com/trieuconcrete/laravel-admin/issues/139
https://github.com/trieuconcrete/laravel-admin/issues/140
https://github.com/trieuconcrete/laravel-admin/issues/141
https://github.com/trieuconcrete/laravel-admin/issues/142
https://github.com/trieuconcrete/laravel-admin/issues/143
> issues_139_140_141_142_143

- src/app/Http/Controllers/Admin/CarRentalController.php
- src/app/Http/Controllers/Admin/CustomerController.php
- src/app/Http/Controllers/Admin/DashboardController.php
- src/app/Http/Controllers/Admin/ShipmentController.php
- src/app/Models/Shipment.php
- src/app/Repositories/Eloquent/ShipmentRepository.php
- src/app/Repositories/Interface/ShipmentRepositoryInterface.php
- src/app/Services/CustomerService.php
- src/app/Services/FinancialCalculationService.php
- src/app/Services/SalaryService.php
- src/app/Services/UserService.php
- src/app/Traits/HasCompletedStatus.php
- src/resources/views/admin/car_rental/edit.blade.php
- src/resources/views/admin/customers/show.blade.php
- src/resources/views/admin/shipments/index.blade.php
- src/routes/web.php
https://github.com/trieuconcrete/laravel-admin/issues/134
https://github.com/trieuconcrete/laravel-admin/issues/144
https://github.com/trieuconcrete/laravel-admin/issues/145
https://github.com/trieuconcrete/laravel-admin/issues/146
https://github.com/trieuconcrete/laravel-admin/issues/149
> issues_134_144_145_146_149

- src/app/Http/Controllers/Admin/SalaryController.php
- src/app/Http/Controllers/Admin/UserController.php
- src/app/Models/SalaryAdvanceRequest.php
- src/app/Models/User.php
- src/app/Services/SalaryService.php
- src/app/Services/UserService.php
- src/database/migrations/2025_07_31_191200_update_salary_advance_requests_type_enum.php
- src/public/js/salary-advance-requests-handler.js
- src/resources/views/admin/shipments/index.blade.php
- src/resources/views/admin/users/partials/salary-table.blade.php
- src/resources/views/admin/users/show_bk.blade.php
https://github.com/trieuconcrete/laravel-admin/issues/139
https://github.com/trieuconcrete/laravel-admin/issues/142
> issues 142, 139

- src/app/Enum/SalaryType.php
- src/app/Http/Requests/User/StoreUserRequest.php
- src/app/Models/SalaryDetail.php
- src/app/Models/User.php
- src/app/Services/SalaryService.php
- src/app/Services/UserService.php
- src/database/migrations/2025_08_06_150000_add_salary_type_to_users_table.php
- src/database/seeders/UpdateSalaryTypeSeeder.php
- src/resources/views/admin/users/index.blade.php
- src/resources/views/admin/users/show.blade.php
https://github.com/trieuconcrete/laravel-admin/issues/175
`run: php artisan migrate`
> Issues 175

- src/app/Http/Controllers/Admin/ShipmentController.php
- src/app/Http/Controllers/Admin/VehicleController.php
- src/app/Http/Requests/Shipment/ShipmentRequest.php
- src/app/Services/ShipmentService.php
- src/public/js/shipment-form.js
- src/resources/views/admin/shipments/create.blade.php
- src/resources/views/admin/shipments/edit.blade.php
https://github.com/trieuconcrete/laravel-admin/issues/176
> Issues 176

- src/app/Http/Controllers/Admin/CarRentalController.php
- src/app/Http/Requests/Shipment/ShipmentRequest.php
- src/app/Models/Shipment.php
- src/app/Services/ShipmentService.php
- src/database/migrations/2025_08_13_111530_add_is_overtime_at_noon_to_shipments_table.php
- src/public/js/car-rental-form.js
- src/resources/css/app.css
- src/resources/views/admin/car_rental/edit.blade.php
- src/resources/views/admin/car_rental/shipments/create.blade.php
- src/resources/views/admin/car_rental/shipments/edit.blade.php
https://github.com/trieuconcrete/laravel-admin/issues/180
Note: chưa bao gồm xuất excel
> Issues 180

- src/app/Exports/ShipmentLogExport.php
- src/app/Exports/ShipmentTollFeeDetailExport.php
- src/app/Exports/ShipmentTollFeeExport.php
- src/app/Http/Controllers/Admin/CarRentalController.php
- src/resources/views/admin/car_rental/shipments/create.blade.php
- src/resources/views/admin/car_rental/shipments/edit.blade.php
https://github.com/trieuconcrete/laravel-admin/issues/180
> Issues 180 step 2

- src/app/Exports/ShipmentTollFeeDetailExport.php
- src/app/Http/Controllers/Admin/CarRentalController.php
- src/app/Models/CarRental.php
- src/app/Models/ShipmentReport.php
- src/database/migrations/2025_08_19_143700_add_car_rental_id_to_shipment_reports_table.php
- src/resources/views/admin/car_rental/edit.blade.php
- src/resources/views/admin/car_rental/index.blade.php
- src/routes/web.php
https://github.com/trieuconcrete/laravel-admin/issues/241
> issues 241 step 2

- src/app/Http/Controllers/Admin/CarRentalController.php
- src/resources/views/admin/car_rental/edit.blade.php
- src/resources/views/admin/car_rental/index.blade.php
https://github.com/trieuconcrete/laravel-admin/issues/241
> issues 241 step 3

- src/app/Exports/ShipmentLogExport.php
- src/app/Http/Controllers/Admin/CarRentalController.php
- src/app/Services/ShipmentService.php
- src/public/js/car-rental-form.js
- src/resources/views/admin/car_rental/edit.blade.php
- src/resources/views/admin/car_rental/index.blade.php
- src/resources/views/admin/car_rental/shipments/create.blade.php
- src/resources/views/admin/car_rental/shipments/edit.blade.php
- src/routes/api.php
https://github.com/trieuconcrete/laravel-admin/issues/258
> issues 258

- src/app/Enum/SalaryType.php
- src/app/Exports/SalaryCommissionExport.php
- src/app/Http/Controllers/Admin/SalaryController.php
- src/app/Http/Controllers/Admin/UserController.php
- src/app/Models/ShipmentDeductionType.php
- src/app/Services/SalaryService.php
- src/app/Services/UserService.php
- src/resources/views/admin/salary/index.blade.php
- src/resources/views/admin/users/show.blade.php
https://github.com/trieuconcrete/laravel-admin/issues/197
> issues 197

- src/app/Exports/OfficeSalaryExport.php
- src/app/Exports/SalaryCommissionExport.php
- src/app/Exports/SalaryExport.php
- src/app/Http/Requests/User/StoreUserRequest.php
- src/app/Http/Requests/User/UpdateUserRequest.php
- src/app/Models/User.php
- src/app/Services/SalaryService.php
- src/app/Services/UserService.php
- src/database/migrations/2025_09_09_100000_add_insurance_fields_to_users_table.php
- src/resources/views/admin/users/index.blade.php
- src/resources/views/admin/users/show.blade.php
run migrate
https://github.com/trieuconcrete/laravel-admin/issues/335
> issues 335

- src/resources/views/admin/settings/partials/vehicle_types.blade.php
> vehicle types crud

- src/app/Exports/SalaryCommissionExport.php
- src/app/Exports/SalaryExport.php
https://github.com/trieuconcrete/laravel-admin/issues/394
> issues 394
